name: GenerateSBOM

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: pwd
    - run: ls
    - name: Generate SBOM artifact
      uses: anchore/sbom-action@v0
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        artifact-name: sbom.spdx.json
