name: GenerateSBOM

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Generate SBOM artifact
      uses: anchore/sbom-action@v0.14.1
      with:
        artifact-name: sbom.spdx.json
